<a href="https://colab.research.google.com/github/ankay212000/Data-Mining-and-Analysis-Practical/blob/main/Exercise6_UE183065.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) 
 
 Output should be

array([[ 0.,  1.,  0.],[ 0.,  0.,  1.],[ 0.,  1.,  0.],[ 0.,  1.,  0.],[ 0.,  1.,  0.],[ 1.,  0.,  0.]])



In [1]:
import numpy as np

def encode(num,arr):
  for i in range(len(arr)):
    num[i][arr[i]-1]=1

  return num

arr=[2,3,2,2,1]
dim=max(arr)
num=np.zeros(dim*len(arr))
num=num.reshape(len(arr),dim)

num=encode(num,arr)
print("one hot encoding: ")
print(num)

one hot encoding: 
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


Drop all missing values from an array Input:

np.array([1,2,3,np.nan,5,6,7,np.nan]) 

Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [80]:
input_arr=np.array([1,2,3,np.nan,5,6,7,np.nan])
output_arr=np.array([])
for i in input_arr:
  if(np.isnan(i)==False):
    output_arr=np.append(output_arr,[i])
print("Output: ")
print(output_arr)

Output: 
[1. 2. 3. 5. 6. 7.]


Find Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
 
Desired Output: array([2, 5])

In [81]:
a=np.array([1,3,7,1,2,6,0,1])
diff_arr=np.array([])
for i in range(1,len(a)):
  diff_arr=np.append(diff_arr,a[i]-a[i-1])

res=np.array([])
for i in range(0,len(diff_arr)):
  if(diff_arr[i]<0):
    res=np.append(res,i)

print("Local Maxima index: ")
print(res)

Local Maxima index: 
[2. 5.]


From the given 1d array arr, generate a 2d matrix using strides,

For example for an array 

([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

with a window length of w=4 and strides of s=2, 

like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

w and s will be provided by user

In [82]:
def generate(num,w,s):
  ans=np.array([])
  flag=True
  for i in range(0,len(num),s):
    for j in range(0,w):
      if(i+j>=len(num)):
        ans=np.append(ans,ans[-1])
        flag=False
      else:
        ans=np.append(ans,num[(i+j)%len(num)])    
    if(flag==False or ans[-1]==num[-1]):
      break    

  ans=ans.reshape(len(ans)//w,w)
  return ans
input_arr=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,14])
wind=int(input("Enter Window Length: "))
strid=int(input("Enter Strides: "))

print("Generated matrix: ")
print(generate(input_arr,wind,strid))
  

Enter Window Length: 4
Enter Strides: 2
Generated matrix: 
[[ 0.  1.  2.  3.]
 [ 2.  3.  4.  5.]
 [ 4.  5.  6.  7.]
 [ 6.  7.  8.  9.]
 [ 8.  9. 10. 11.]
 [10. 11. 12. 13.]
 [12. 13. 14. 14.]]
